# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_ui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.window = QtWidgets.QFrame(self.centralwidget)
        self.window.setGeometry(QtCore.QRect(-10, -10, 671, 441))
        self.window.setMaximumSize(QtCore.QSize(671, 441))
        self.window.setAutoFillBackground(False)
        self.window.setStyleSheet("")
        self.window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window.setObjectName("window")
        self.window_2 = QtWidgets.QFrame(self.window)
        self.window_2.setGeometry(QtCore.QRect(20, 20, 181, 371))
        self.window_2.setStyleSheet("QFrame {\n"
"    border: 0.5px dashed;\n"
"    border-radius: 10px;\n"
"    border-top-color: black; \n"
"    border-left-color: black;\n"
"    border-right-color: black;\n"
"    border-bottom-color: black;\n"
"}")
        self.window_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_2.setObjectName("window_2")
        self.frame_grip_2 = QtWidgets.QFrame(self.window_2)
        self.frame_grip_2.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_2.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_2.setObjectName("frame_grip_2")
        self.DNALabel = QtWidgets.QLabel(self.window_2)
        self.DNALabel.setGeometry(QtCore.QRect(10, -10, 161, 61))
        self.DNALabel.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 13pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel.setObjectName("DNALabel")
        self.DNALabel_9 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_9.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.DNALabel_9.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    border: 0px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"}")
        self.DNALabel_9.setObjectName("DNALabel_9")
        self.name = QtWidgets.QLineEdit(self.window_2)
        self.name.setGeometry(QtCore.QRect(60, 50, 111, 21))
        self.name.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    border: 10px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.name.setText("")
        self.name.setObjectName("name")
        self.DNALabel_10 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_10.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.DNALabel_10.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_10.setObjectName("DNALabel_10")
        self.total_time = QtWidgets.QLineEdit(self.window_2)
        self.total_time.setGeometry(QtCore.QRect(110, 80, 31, 21))
        self.total_time.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.total_time.setText("")
        self.total_time.setReadOnly(True)
        self.total_time.setObjectName("total_time")
        self.DNALabel_11 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_11.setGeometry(QtCore.QRect(150, 80, 21, 21))
        self.DNALabel_11.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_11.setObjectName("DNALabel_11")
        self.line = QtWidgets.QFrame(self.window_2)
        self.line.setGeometry(QtCore.QRect(30, 120, 118, 3))
        self.line.setStyleSheet("border-radius: 8px;\n"
"border: 1px solid;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.DNALabel_13 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_13.setGeometry(QtCore.QRect(10, 140, 171, 21))
        self.DNALabel_13.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    border: 0px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"}")
        self.DNALabel_13.setObjectName("DNALabel_13")
        self.classic = QtWidgets.QCheckBox(self.window_2)
        self.classic.setGeometry(QtCore.QRect(30, 170, 141, 18))
        self.classic.setStyleSheet("border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"background-color: rgb(252, 252, 252);\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";")
        self.classic.setTristate(False)
        self.classic.setObjectName("classic")
        self.electronic = QtWidgets.QCheckBox(self.window_2)
        self.electronic.setGeometry(QtCore.QRect(30, 210, 141, 18))
        self.electronic.setStyleSheet("border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"background-color: rgb(252, 252, 252);\n"
"    font: 63 8pt \"Cascadia Code SemiBold\";")
        self.electronic.setObjectName("electronic")
        self.lofi = QtWidgets.QCheckBox(self.window_2)
        self.lofi.setGeometry(QtCore.QRect(30, 190, 141, 18))
        self.lofi.setStyleSheet("border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"background-color: rgb(252, 252, 252);")
        self.lofi.setObjectName("lofi")
        self.line_2 = QtWidgets.QFrame(self.window_2)
        self.line_2.setGeometry(QtCore.QRect(30, 250, 118, 3))
        self.line_2.setStyleSheet("border-radius: 8px;\n"
"border: 1px solid;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.DNALabel_14 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_14.setGeometry(QtCore.QRect(10, 270, 121, 21))
        self.DNALabel_14.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_14.setObjectName("DNALabel_14")
        self.DNALabel_15 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_15.setGeometry(QtCore.QRect(10, 300, 161, 21))
        self.DNALabel_15.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_15.setObjectName("DNALabel_15")
        self.am_bt = QtWidgets.QPushButton(self.window_2)
        self.am_bt.setGeometry(QtCore.QRect(30, 330, 51, 31))
        self.am_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(240, 240, 240);}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.am_bt.setObjectName("am_bt")
        self.pm_bt = QtWidgets.QPushButton(self.window_2)
        self.pm_bt.setGeometry(QtCore.QRect(100, 330, 51, 31))
        self.pm_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #edb4a1;\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"background-color: rgb(252, 252, 252);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(240, 240, 240);}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pm_bt.setObjectName("pm_bt")
        self.date = QtWidgets.QLineEdit(self.window_2)
        self.date.setGeometry(QtCore.QRect(60, 270, 111, 21))
        self.date.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.date.setText("")
        self.date.setReadOnly(True)
        self.date.setObjectName("date")
        self.time_input = QtWidgets.QLineEdit(self.window_2)
        self.time_input.setGeometry(QtCore.QRect(60, 300, 111, 21))
        self.time_input.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.time_input.setText("")
        self.time_input.setReadOnly(True)
        self.time_input.setObjectName("time_input")
        self.window_3 = QtWidgets.QFrame(self.window)
        self.window_3.setGeometry(QtCore.QRect(210, 20, 421, 51))
        self.window_3.setStyleSheet("QFrame {\n"
"    border: 0.5px dashed;\n"
"    border-radius: 10px;\n"
"    border-top-color: black; \n"
"    border-left-color: black;\n"
"    border-right-color: black;\n"
"    border-bottom-color: black;\n"
"}")
        self.window_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_3.setObjectName("window_3")
        self.frame_grip_3 = QtWidgets.QFrame(self.window_3)
        self.frame_grip_3.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_3.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_3.setObjectName("frame_grip_3")
        self.min = QtWidgets.QLineEdit(self.window_3)
        self.min.setGeometry(QtCore.QRect(70, 16, 41, 20))
        self.min.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.min.setText("")
        self.min.setObjectName("min")
        self.DNALabel_8 = QtWidgets.QLabel(self.window_3)
        self.DNALabel_8.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.DNALabel_8.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    border: 0px;\n"
"    color: #edb4a1;\n"
"    font: 25 13pt \"Cascadia Code Light\";\n"
"}")
        self.DNALabel_8.setObjectName("DNALabel_8")
        self.start_bt = QtWidgets.QPushButton(self.window_3)
        self.start_bt.setGeometry(QtCore.QRect(310, 16, 41, 20))
        self.start_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #edb4a1;\n"
"background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    color: rgb(203, 154, 138);\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.start_bt.setObjectName("start_bt")
        self.music_bt = QtWidgets.QPushButton(self.window_3)
        self.music_bt.setGeometry(QtCore.QRect(360, 16, 51, 20))
        self.music_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(72, 112, 86);\n"
"background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    color: rgb(203, 154, 138);\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.music_bt.setObjectName("music_bt")
        self.project_name = QtWidgets.QLineEdit(self.window_3)
        self.project_name.setGeometry(QtCore.QRect(180, 16, 121, 20))
        self.project_name.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.project_name.setInputMask("")
        self.project_name.setObjectName("project_name")
        self.DNALabel_12 = QtWidgets.QLabel(self.window_3)
        self.DNALabel_12.setGeometry(QtCore.QRect(115, 9, 16, 31))
        self.DNALabel_12.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_12.setObjectName("DNALabel_12")
        self.sec = QtWidgets.QLineEdit(self.window_3)
        self.sec.setGeometry(QtCore.QRect(130, 16, 41, 20))
        self.sec.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.sec.setText("")
        self.sec.setObjectName("sec")
        self.window_4 = QtWidgets.QFrame(self.window)
        self.window_4.setGeometry(QtCore.QRect(210, 80, 421, 311))
        self.window_4.setStyleSheet("QFrame {\n"
"    border: 0.5px dashed;\n"
"    border-radius: 10px;\n"
"    border-top-color: black; \n"
"    border-left-color: black;\n"
"    border-right-color: black;\n"
"    border-bottom-color: black;\n"
"}")
        self.window_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_4.setObjectName("window_4")
        self.frame_grip_5 = QtWidgets.QFrame(self.window_4)
        self.frame_grip_5.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_5.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_5.setObjectName("frame_grip_5")
        self.enter = QtWidgets.QPushButton(self.window_4)
        self.enter.setGeometry(QtCore.QRect(20, 280, 61, 20))
        self.enter.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #edb4a1;\n"
"    background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    color: rgb(203, 154, 138);\n"
"    background-color:  rgb(240, 240, 240);\n"
"}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.enter.setObjectName("enter")
        self.clear = QtWidgets.QPushButton(self.window_4)
        self.clear.setGeometry(QtCore.QRect(240, 280, 61, 21))
        self.clear.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(80, 125, 97);\n"
"    background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.clear.setObjectName("clear")
        self.task_name = QtWidgets.QLineEdit(self.window_4)
        self.task_name.setGeometry(QtCore.QRect(20, 250, 281, 21))
        self.task_name.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.task_name.setText("")
        self.task_name.setObjectName("task_name")
        self.DNALabel_6 = QtWidgets.QLabel(self.window_4)
        self.DNALabel_6.setGeometry(QtCore.QRect(160, -10, 101, 61))
        self.DNALabel_6.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 13pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_6.setObjectName("DNALabel_6")
        self.task_num = QtWidgets.QLineEdit(self.window_4)
        self.task_num.setGeometry(QtCore.QRect(340, 250, 61, 21))
        self.task_num.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.task_num.setText("")
        self.task_num.setObjectName("task_num")
        self.DNALabel_7 = QtWidgets.QLabel(self.window_4)
        self.DNALabel_7.setGeometry(QtCore.QRect(330, 250, 20, 21))
        self.DNALabel_7.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_7.setObjectName("DNALabel_7")
        self.delete_bt = QtWidgets.QPushButton(self.window_4)
        self.delete_bt.setGeometry(QtCore.QRect(330, 280, 71, 21))
        self.delete_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(80, 125, 97);\n"
"    background-color: rgb(255, 0, 0);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(222, 0, 0);\n"
"}")
        self.delete_bt.setObjectName("delete_bt")
        self.all_tasks = QtWidgets.QPlainTextEdit(self.window_4)
        self.all_tasks.setGeometry(QtCore.QRect(20, 40, 381, 201))
        self.all_tasks.setStyleSheet("border: 0px solid;\n"
"border-color: none;\n"
"border-radius: 6px;\n"
"    color: #edb4a1;\n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";")
        self.all_tasks.setReadOnly(True)
        self.all_tasks.setObjectName("all_tasks")
        self.frame_grip_5.raise_()
        self.enter.raise_()
        self.clear.raise_()
        self.task_name.raise_()
        self.DNALabel_6.raise_()
        self.DNALabel_7.raise_()
        self.task_num.raise_()
        self.delete_bt.raise_()
        self.all_tasks.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DNALabel.setText(_translate("MainWindow", "Profile Overview"))
        self.DNALabel_9.setText(_translate("MainWindow", "Name:"))
        self.DNALabel_10.setText(_translate("MainWindow", "Total Time:"))
        self.DNALabel_11.setText(_translate("MainWindow", "hr"))
        self.DNALabel_13.setText(_translate("MainWindow", "Music Preferences:"))
        self.classic.setText(_translate("MainWindow", "Classical Music"))
        self.electronic.setText(_translate("MainWindow", "Electronic Music"))
        self.lofi.setText(_translate("MainWindow", "Lo-Fi Music"))
        self.DNALabel_14.setText(_translate("MainWindow", "Date:"))
        self.DNALabel_15.setText(_translate("MainWindow", "Time:"))
        self.am_bt.setText(_translate("MainWindow", "☀️"))
        self.pm_bt.setText(_translate("MainWindow", "🌚"))
        self.DNALabel_8.setText(_translate("MainWindow", "Timer"))
        self.start_bt.setText(_translate("MainWindow", "▷"))
        self.music_bt.setText(_translate("MainWindow", "🎼"))
        self.project_name.setText(_translate("MainWindow", "Project Name"))
        self.DNALabel_12.setText(_translate("MainWindow", ":"))
        self.enter.setText(_translate("MainWindow", "⇒"))
        self.clear.setText(_translate("MainWindow", "🧹"))
        self.DNALabel_6.setText(_translate("MainWindow", "Task List"))
        self.DNALabel_7.setText(_translate("MainWindow", "#"))
        self.delete_bt.setText(_translate("MainWindow", "🗑️"))
        self.all_tasks.setPlainText(_translate("MainWindow", "Task 1:"))
