# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\prana\OneDrive\Desktop\Documents\My Files\Projects\Procrastinator\app_ui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.window = QtWidgets.QFrame(self.centralwidget)
        self.window.setGeometry(QtCore.QRect(-10, -10, 671, 441))
        self.window.setMaximumSize(QtCore.QSize(671, 441))
        self.window.setAutoFillBackground(False)
        self.window.setStyleSheet("")
        self.window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window.setObjectName("window")
        self.window_2 = QtWidgets.QFrame(self.window)
        self.window_2.setGeometry(QtCore.QRect(20, 20, 181, 371))
        self.window_2.setStyleSheet("QFrame {\n"
"    \n"
"}")
        self.window_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_2.setObjectName("window_2")
        self.frame_grip_2 = QtWidgets.QFrame(self.window_2)
        self.frame_grip_2.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_2.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_2.setObjectName("frame_grip_2")
        self.DNALabel = QtWidgets.QLabel(self.window_2)
        self.DNALabel.setGeometry(QtCore.QRect(10, -10, 161, 61))
        self.DNALabel.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 13pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel.setObjectName("DNALabel")
        self.DNALabel_9 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_9.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.DNALabel_9.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    border: 0px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"}")
        self.DNALabel_9.setObjectName("DNALabel_9")
        self.name = QtWidgets.QLineEdit(self.window_2)
        self.name.setGeometry(QtCore.QRect(60, 50, 111, 21))
        self.name.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    border: 10px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.name.setText("")
        self.name.setObjectName("name")
        self.DNALabel_10 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_10.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.DNALabel_10.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_10.setObjectName("DNALabel_10")
        self.total_time = QtWidgets.QLineEdit(self.window_2)
        self.total_time.setGeometry(QtCore.QRect(110, 80, 31, 21))
        self.total_time.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.total_time.setText("")
        self.total_time.setReadOnly(True)
        self.total_time.setObjectName("total_time")
        self.DNALabel_11 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_11.setGeometry(QtCore.QRect(150, 80, 21, 21))
        self.DNALabel_11.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_11.setObjectName("DNALabel_11")
        self.DNALabel_13 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_13.setGeometry(QtCore.QRect(10, 140, 171, 21))
        self.DNALabel_13.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    border: 0px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"}")
        self.DNALabel_13.setObjectName("DNALabel_13")
        self.classic = QtWidgets.QCheckBox(self.window_2)
        self.classic.setGeometry(QtCore.QRect(30, 170, 141, 18))
        self.classic.setStyleSheet("border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"background-color: rgb(252, 252, 252);\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";")
        self.classic.setTristate(False)
        self.classic.setObjectName("classic")
        self.electronic = QtWidgets.QCheckBox(self.window_2)
        self.electronic.setGeometry(QtCore.QRect(30, 210, 141, 18))
        self.electronic.setStyleSheet("border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"background-color: rgb(252, 252, 252);\n"
"    font: 63 8pt \"Cascadia Code SemiBold\";")
        self.electronic.setObjectName("electronic")
        self.lofi = QtWidgets.QCheckBox(self.window_2)
        self.lofi.setGeometry(QtCore.QRect(30, 190, 141, 18))
        self.lofi.setStyleSheet("border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"background-color: rgb(252, 252, 252);")
        self.lofi.setObjectName("lofi")
        self.DNALabel_14 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_14.setGeometry(QtCore.QRect(10, 270, 121, 21))
        self.DNALabel_14.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_14.setObjectName("DNALabel_14")
        self.DNALabel_15 = QtWidgets.QLabel(self.window_2)
        self.DNALabel_15.setGeometry(QtCore.QRect(10, 300, 161, 21))
        self.DNALabel_15.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_15.setObjectName("DNALabel_15")
        self.am_bt = QtWidgets.QPushButton(self.window_2)
        self.am_bt.setGeometry(QtCore.QRect(30, 330, 51, 31))
        self.am_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(240, 240, 240);}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.am_bt.setObjectName("am_bt")
        self.pm_bt = QtWidgets.QPushButton(self.window_2)
        self.pm_bt.setGeometry(QtCore.QRect(100, 330, 51, 31))
        self.pm_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #edb4a1;\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"background-color: rgb(252, 252, 252);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(240, 240, 240);}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pm_bt.setObjectName("pm_bt")
        self.date = QtWidgets.QLineEdit(self.window_2)
        self.date.setGeometry(QtCore.QRect(60, 270, 111, 21))
        self.date.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.date.setText("")
        self.date.setReadOnly(True)
        self.date.setObjectName("date")
        self.time_input = QtWidgets.QLineEdit(self.window_2)
        self.time_input.setGeometry(QtCore.QRect(60, 300, 111, 21))
        self.time_input.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.time_input.setText("")
        self.time_input.setReadOnly(True)
        self.time_input.setObjectName("time_input")
        self.border = QtWidgets.QLineEdit(self.window_2)
        self.border.setGeometry(QtCore.QRect(20, 121, 145, 3))
        self.border.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    border: 2px solid;\n"
"    border-top-color:  rgb(219, 167, 149);\n"
"    border-right-color:  rgb(219, 167, 149);\n"
"    border-left-color:  rgb(219, 167, 149);\n"
"border-bottom-color: rgb(219, 167, 149);\n"
"    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.border.setText("")
        self.border.setDragEnabled(False)
        self.border.setReadOnly(True)
        self.border.setObjectName("border")
        self.border_2 = QtWidgets.QLineEdit(self.window_2)
        self.border_2.setGeometry(QtCore.QRect(20, 246, 145, 3))
        self.border_2.setStyleSheet("\n"
"    border-radius: 3px;\n"
"    border: 2px solid;\n"
"    border-top-color:  rgb(219, 167, 149);\n"
"    border-right-color:  rgb(219, 167, 149);\n"
"    border-left-color:  rgb(219, 167, 149);\n"
"border-bottom-color: rgb(219, 167, 149);\n"
"")
        self.border_2.setText("")
        self.border_2.setDragEnabled(False)
        self.border_2.setReadOnly(True)
        self.border_2.setObjectName("border_2")
        self.frame = QtWidgets.QFrame(self.window_2)
        self.frame.setGeometry(QtCore.QRect(6, 10, 169, 21))
        self.frame.setStyleSheet("QFrame {\n"
"border: 1px solid;\n"
"border-radius: 6px;\n"
"border-top-color: rgb(237, 180, 161);\n"
"border-right-color: rgb(237, 180, 161);\n"
"border-left-color: rgb(237, 180, 161);\n"
"border-bottom-color: rgb(237, 180, 161);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.window_5 = QtWidgets.QFrame(self.window_2)
        self.window_5.setGeometry(QtCore.QRect(0, 0, 181, 371))
        self.window_5.setStyleSheet("QFrame {\n"
"    border: 1px solid;\n"
"    border-radius: 5px;\n"
"    border-bottom-color: rgb(222, 169, 151);\n"
"border-right-color: rgb(222, 169, 151);\n"
"border-left-color: rgb(222, 169, 151);\n"
"    border-top-color: rgb(222, 169, 151);\n"
"}")
        self.window_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_5.setObjectName("window_5")
        self.frame_grip_4 = QtWidgets.QFrame(self.window_5)
        self.frame_grip_4.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_4.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_4.setObjectName("frame_grip_4")
        self.window_5.raise_()
        self.border.raise_()
        self.frame_grip_2.raise_()
        self.DNALabel.raise_()
        self.DNALabel_9.raise_()
        self.name.raise_()
        self.DNALabel_10.raise_()
        self.total_time.raise_()
        self.DNALabel_11.raise_()
        self.DNALabel_13.raise_()
        self.classic.raise_()
        self.electronic.raise_()
        self.lofi.raise_()
        self.DNALabel_14.raise_()
        self.DNALabel_15.raise_()
        self.am_bt.raise_()
        self.pm_bt.raise_()
        self.date.raise_()
        self.time_input.raise_()
        self.border_2.raise_()
        self.frame.raise_()
        self.window_3 = QtWidgets.QFrame(self.window)
        self.window_3.setGeometry(QtCore.QRect(210, 20, 421, 51))
        self.window_3.setStyleSheet("")
        self.window_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_3.setObjectName("window_3")
        self.frame_grip_3 = QtWidgets.QFrame(self.window_3)
        self.frame_grip_3.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_3.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_3.setObjectName("frame_grip_3")
        self.hour = QtWidgets.QLineEdit(self.window_3)
        self.hour.setGeometry(QtCore.QRect(70, 16, 41, 20))
        self.hour.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.hour.setText("")
        self.hour.setObjectName("hour")
        self.DNALabel_8 = QtWidgets.QLabel(self.window_3)
        self.DNALabel_8.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.DNALabel_8.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    border: 0px;\n"
"    color: #edb4a1;\n"
"    font: 25 13pt \"Cascadia Code Light\";\n"
"}")
        self.DNALabel_8.setObjectName("DNALabel_8")
        self.start_bt = QtWidgets.QPushButton(self.window_3)
        self.start_bt.setGeometry(QtCore.QRect(360, 16, 41, 20))
        self.start_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #edb4a1;\n"
"background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    color: rgb(203, 154, 138);\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.start_bt.setObjectName("start_bt")
        self.project_name = QtWidgets.QLineEdit(self.window_3)
        self.project_name.setGeometry(QtCore.QRect(180, 16, 171, 20))
        self.project_name.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.project_name.setInputMask("")
        self.project_name.setObjectName("project_name")
        self.DNALabel_12 = QtWidgets.QLabel(self.window_3)
        self.DNALabel_12.setGeometry(QtCore.QRect(115, 9, 16, 31))
        self.DNALabel_12.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_12.setObjectName("DNALabel_12")
        self.min = QtWidgets.QLineEdit(self.window_3)
        self.min.setGeometry(QtCore.QRect(130, 16, 41, 20))
        self.min.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.min.setText("")
        self.min.setObjectName("min")
        self.frame_3 = QtWidgets.QFrame(self.window_3)
        self.frame_3.setGeometry(QtCore.QRect(5, 15, 61, 21))
        self.frame_3.setStyleSheet("QFrame {\n"
"border: 1px solid;\n"
"border-radius: 6px;\n"
"border-top-color: rgb(237, 180, 161);\n"
"border-right-color: rgb(237, 180, 161);\n"
"border-left-color: rgb(237, 180, 161);\n"
"border-bottom-color: rgb(237, 180, 161);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.window_7 = QtWidgets.QFrame(self.window_3)
        self.window_7.setGeometry(QtCore.QRect(0, 0, 421, 51))
        self.window_7.setStyleSheet("QFrame {\n"
"    border: 1px solid;\n"
"    border-radius: 5px;\n"
"    border-bottom-color: rgb(222, 169, 151);\n"
"border-right-color: rgb(222, 169, 151);\n"
"border-left-color: rgb(222, 169, 151);\n"
"    border-top-color: rgb(222, 169, 151);\n"
"}")
        self.window_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_7.setObjectName("window_7")
        self.frame_grip_7 = QtWidgets.QFrame(self.window_7)
        self.frame_grip_7.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_7.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_7.setObjectName("frame_grip_7")
        self.frame_3.raise_()
        self.window_7.raise_()
        self.frame_grip_3.raise_()
        self.hour.raise_()
        self.DNALabel_8.raise_()
        self.start_bt.raise_()
        self.project_name.raise_()
        self.DNALabel_12.raise_()
        self.min.raise_()
        self.window_4 = QtWidgets.QFrame(self.window)
        self.window_4.setGeometry(QtCore.QRect(210, 80, 421, 311))
        self.window_4.setStyleSheet("")
        self.window_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_4.setObjectName("window_4")
        self.frame_grip_5 = QtWidgets.QFrame(self.window_4)
        self.frame_grip_5.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_5.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_5.setObjectName("frame_grip_5")
        self.enter = QtWidgets.QPushButton(self.window_4)
        self.enter.setGeometry(QtCore.QRect(20, 280, 61, 20))
        self.enter.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #edb4a1;\n"
"    background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    color: rgb(203, 154, 138);\n"
"    background-color:  rgb(240, 240, 240);\n"
"}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.enter.setObjectName("enter")
        self.down_bt = QtWidgets.QPushButton(self.window_4)
        self.down_bt.setGeometry(QtCore.QRect(270, 280, 31, 21))
        self.down_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(80, 125, 97);\n"
"    background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.down_bt.setObjectName("down_bt")
        self.task_name = QtWidgets.QLineEdit(self.window_4)
        self.task_name.setGeometry(QtCore.QRect(20, 250, 281, 21))
        self.task_name.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.task_name.setText("")
        self.task_name.setObjectName("task_name")
        self.DNALabel_6 = QtWidgets.QLabel(self.window_4)
        self.DNALabel_6.setGeometry(QtCore.QRect(160, 0, 101, 51))
        self.DNALabel_6.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 13pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_6.setObjectName("DNALabel_6")
        self.task_num = QtWidgets.QLineEdit(self.window_4)
        self.task_num.setGeometry(QtCore.QRect(340, 250, 61, 21))
        self.task_num.setStyleSheet("QLineEdit {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 63 8pt \"Cascadia Code SemiBold\";\n"
"}")
        self.task_num.setText("")
        self.task_num.setObjectName("task_num")
        self.DNALabel_7 = QtWidgets.QLabel(self.window_4)
        self.DNALabel_7.setGeometry(QtCore.QRect(330, 250, 20, 21))
        self.DNALabel_7.setStyleSheet("QLabel {\n"
"    border-radius: 3px;\n"
"    color: #edb4a1;\n"
"    font: 25 11pt \"Cascadia Code Light\";\n"
"border: 0px;\n"
"}")
        self.DNALabel_7.setObjectName("DNALabel_7")
        self.delete_bt = QtWidgets.QPushButton(self.window_4)
        self.delete_bt.setGeometry(QtCore.QRect(330, 280, 71, 21))
        self.delete_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(80, 125, 97);\n"
"    background-color: rgb(252, 252, 252);\n"
"    border: 1px solid;\n"
"    border-top-color: rgb(255, 0, 0);\n"
"    border-right-color: rgb(255, 0, 0);\n"
"    border-left-color: rgb(255, 0, 0);\n"
"    border-bottom-color: rgb(255, 0, 0);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border-top-color: rgb(227, 0, 0);\n"
"    border-right-color: rgb(227, 0, 0);\n"
"    border-left-color: rgb(227, 0, 0);\n"
"    border-bottom-color: rgb(227, 0, 0);\n"
"}")
        self.delete_bt.setObjectName("delete_bt")
        self.all_tasks = QtWidgets.QPlainTextEdit(self.window_4)
        self.all_tasks.setGeometry(QtCore.QRect(20, 50, 381, 191))
        self.all_tasks.setStyleSheet("             QPlainTextEdit{\n"
"             border: 0px solid;\n"
"             border-color: none;\n"
"             border-radius: 6px;\n"
"             color: #edb4a1;\n"
"             font: 63 8pt \"Cascadia Code SemiBold\";\n"
"             }\n"
"        QScrollBar:vertical {\n"
"            border: 0px solid #dca795;\n"
"            background:white;   \n"
"            margin: 0px 0px 0px 0px;\n"
"               width: 1px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"       \n"
"            min-height: 0px;\n"
"              border: 0px solid red;\n"
"            border-radius: 5px;\n"
"            background-color: #dca795;\n"
"        }\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"")
        self.all_tasks.setReadOnly(True)
        self.all_tasks.setObjectName("all_tasks")
        self.frame_2 = QtWidgets.QFrame(self.window_4)
        self.frame_2.setGeometry(QtCore.QRect(150, 15, 111, 21))
        self.frame_2.setStyleSheet("QFrame {\n"
"border: 1px solid;\n"
"border-radius: 6px;\n"
"border-top-color: rgb(237, 180, 161);\n"
"border-right-color: rgb(237, 180, 161);\n"
"border-left-color: rgb(237, 180, 161);\n"
"border-bottom-color: rgb(237, 180, 161);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.window_6 = QtWidgets.QFrame(self.window_4)
        self.window_6.setGeometry(QtCore.QRect(0, 0, 421, 311))
        self.window_6.setStyleSheet("QFrame {\n"
"    border: 1px solid;\n"
"    border-radius: 5px;\n"
"    border-bottom-color: rgb(222, 169, 151);\n"
"border-right-color: rgb(222, 169, 151);\n"
"border-left-color: rgb(222, 169, 151);\n"
"    border-top-color: rgb(222, 169, 151);\n"
"}")
        self.window_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_6.setObjectName("window_6")
        self.frame_grip_6 = QtWidgets.QFrame(self.window_6)
        self.frame_grip_6.setGeometry(QtCore.QRect(490, 270, 19, 19))
        self.frame_grip_6.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"}")
        self.frame_grip_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip_6.setObjectName("frame_grip_6")
        self.clear = QtWidgets.QPushButton(self.window_6)
        self.clear.setGeometry(QtCore.QRect(90, 280, 61, 21))
        self.clear.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(80, 125, 97);\n"
"    background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.clear.setObjectName("clear")
        self.up_bt = QtWidgets.QPushButton(self.window_6)
        self.up_bt.setGeometry(QtCore.QRect(230, 280, 31, 21))
        self.up_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(80, 125, 97);\n"
"    background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.up_bt.setObjectName("up_bt")
        self.editTask = QtWidgets.QPushButton(self.window_6)
        self.editTask.setGeometry(QtCore.QRect(190, 280, 31, 20))
        self.editTask.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: #edb4a1;\n"
"background-color: rgb(252, 252, 252);\n"
"    font: 11pt \"Cascadia Code\";\n"
"    padding-bottom: 2px;\n"
"}\n"
"QPushButton::hover {\n"
"    color: rgb(203, 154, 138);\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"QPushButton::disabled {\n"
"    color: rgb(108, 108, 108);\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.editTask.setObjectName("editTask")
        self.window_6.raise_()
        self.frame_2.raise_()
        self.frame_grip_5.raise_()
        self.enter.raise_()
        self.down_bt.raise_()
        self.task_name.raise_()
        self.DNALabel_6.raise_()
        self.DNALabel_7.raise_()
        self.task_num.raise_()
        self.delete_bt.raise_()
        self.all_tasks.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DNALabel.setText(_translate("MainWindow", "Profile Overview"))
        self.DNALabel_9.setText(_translate("MainWindow", "Name:"))
        self.DNALabel_10.setText(_translate("MainWindow", "Total Time:"))
        self.DNALabel_11.setText(_translate("MainWindow", "hr"))
        self.DNALabel_13.setText(_translate("MainWindow", "Music Preferences:"))
        self.classic.setText(_translate("MainWindow", "Classical Music"))
        self.electronic.setText(_translate("MainWindow", "Electronic Music"))
        self.lofi.setText(_translate("MainWindow", "Lo-Fi Music"))
        self.DNALabel_14.setText(_translate("MainWindow", "Date:"))
        self.DNALabel_15.setText(_translate("MainWindow", "Time:"))
        self.am_bt.setText(_translate("MainWindow", "☀️"))
        self.pm_bt.setText(_translate("MainWindow", "🌚"))
        self.DNALabel_8.setText(_translate("MainWindow", "Timer"))
        self.start_bt.setText(_translate("MainWindow", "▷"))
        self.project_name.setText(_translate("MainWindow", "Project Name"))
        self.DNALabel_12.setText(_translate("MainWindow", ":"))
        self.enter.setText(_translate("MainWindow", "⇒"))
        self.down_bt.setText(_translate("MainWindow", "🔽"))
        self.DNALabel_6.setText(_translate("MainWindow", "Task List"))
        self.DNALabel_7.setText(_translate("MainWindow", "#"))
        self.delete_bt.setText(_translate("MainWindow", "🗑️"))
        self.all_tasks.setPlainText(_translate("MainWindow", "Task 1:\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
""))
        self.clear.setText(_translate("MainWindow", "🧹"))
        self.up_bt.setText(_translate("MainWindow", "🔼"))
        self.editTask.setText(_translate("MainWindow", "🖋️"))
